/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthUserIndexRouteImport } from './routes/_auth/user/index'
import { Route as AuthUserStatisticsRouteImport } from './routes/_auth/user/statistics'
import { Route as AuthUserSettingsRouteImport } from './routes/_auth/user/settings'
import { Route as AuthUserPostRouteImport } from './routes/_auth/user/post'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthUserIndexRoute = AuthUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserStatisticsRoute = AuthUserStatisticsRouteImport.update({
  id: '/user/statistics',
  path: '/user/statistics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserSettingsRoute = AuthUserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserPostRoute = AuthUserPostRouteImport.update({
  id: '/user/post',
  path: '/user/post',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/user/post': typeof AuthUserPostRoute
  '/user/settings': typeof AuthUserSettingsRoute
  '/user/statistics': typeof AuthUserStatisticsRoute
  '/user/': typeof AuthUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/user/post': typeof AuthUserPostRoute
  '/user/settings': typeof AuthUserSettingsRoute
  '/user/statistics': typeof AuthUserStatisticsRoute
  '/user': typeof AuthUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_auth/user/post': typeof AuthUserPostRoute
  '/_auth/user/settings': typeof AuthUserSettingsRoute
  '/_auth/user/statistics': typeof AuthUserStatisticsRoute
  '/_auth/user/': typeof AuthUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/user/post'
    | '/user/settings'
    | '/user/statistics'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/user/post'
    | '/user/settings'
    | '/user/statistics'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_public/login'
    | '/_public/signup'
    | '/_auth/user/post'
    | '/_auth/user/settings'
    | '/_auth/user/statistics'
    | '/_auth/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/user/': {
      id: '/_auth/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthUserIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/statistics': {
      id: '/_auth/user/statistics'
      path: '/user/statistics'
      fullPath: '/user/statistics'
      preLoaderRoute: typeof AuthUserStatisticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/settings': {
      id: '/_auth/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof AuthUserSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/post': {
      id: '/_auth/user/post'
      path: '/user/post'
      fullPath: '/user/post'
      preLoaderRoute: typeof AuthUserPostRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthUserPostRoute: typeof AuthUserPostRoute
  AuthUserSettingsRoute: typeof AuthUserSettingsRoute
  AuthUserStatisticsRoute: typeof AuthUserStatisticsRoute
  AuthUserIndexRoute: typeof AuthUserIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUserPostRoute: AuthUserPostRoute,
  AuthUserSettingsRoute: AuthUserSettingsRoute,
  AuthUserStatisticsRoute: AuthUserStatisticsRoute,
  AuthUserIndexRoute: AuthUserIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
