/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoIdRouteImport } from './routes/photo/$id'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthProfileRouteRouteImport } from './routes/_auth/profile/route'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthProfileStatisticsRouteImport } from './routes/_auth/profile/statistics'
import { Route as AuthProfileCreateRouteImport } from './routes/_auth/profile/create'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthProfileRouteRoute = AuthProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProfileRouteRoute,
} as any)
const AuthProfileStatisticsRoute = AuthProfileStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthProfileRouteRoute,
} as any)
const AuthProfileCreateRoute = AuthProfileCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof AuthProfileRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/photo/$id': typeof PhotoIdRoute
  '/profile/create': typeof AuthProfileCreateRoute
  '/profile/statistics': typeof AuthProfileStatisticsRoute
  '/profile/': typeof AuthProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/photo/$id': typeof PhotoIdRoute
  '/profile/create': typeof AuthProfileCreateRoute
  '/profile/statistics': typeof AuthProfileStatisticsRoute
  '/profile': typeof AuthProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/profile': typeof AuthProfileRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/photo/$id': typeof PhotoIdRoute
  '/_auth/profile/create': typeof AuthProfileCreateRoute
  '/_auth/profile/statistics': typeof AuthProfileStatisticsRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/login'
    | '/signup'
    | '/photo/$id'
    | '/profile/create'
    | '/profile/statistics'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/photo/$id'
    | '/profile/create'
    | '/profile/statistics'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_auth/profile'
    | '/_public/login'
    | '/_public/signup'
    | '/photo/$id'
    | '/_auth/profile/create'
    | '/_auth/profile/statistics'
    | '/_auth/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  PhotoIdRoute: typeof PhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthProfileRouteRoute
    }
    '/_auth/profile/statistics': {
      id: '/_auth/profile/statistics'
      path: '/statistics'
      fullPath: '/profile/statistics'
      preLoaderRoute: typeof AuthProfileStatisticsRouteImport
      parentRoute: typeof AuthProfileRouteRoute
    }
    '/_auth/profile/create': {
      id: '/_auth/profile/create'
      path: '/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof AuthProfileCreateRouteImport
      parentRoute: typeof AuthProfileRouteRoute
    }
  }
}

interface AuthProfileRouteRouteChildren {
  AuthProfileCreateRoute: typeof AuthProfileCreateRoute
  AuthProfileStatisticsRoute: typeof AuthProfileStatisticsRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
}

const AuthProfileRouteRouteChildren: AuthProfileRouteRouteChildren = {
  AuthProfileCreateRoute: AuthProfileCreateRoute,
  AuthProfileStatisticsRoute: AuthProfileStatisticsRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
}

const AuthProfileRouteRouteWithChildren =
  AuthProfileRouteRoute._addFileChildren(AuthProfileRouteRouteChildren)

interface AuthRouteChildren {
  AuthProfileRouteRoute: typeof AuthProfileRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRouteRoute: AuthProfileRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  PhotoIdRoute: PhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
